spring:
  application:
    # 配置服务器应用名称
    name: gis-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
          #search-locations: /opt/apps/config-center/config-repo
          #search-locations: E:/Coding IdeaProjects/config-repo
    bus:
      trace:
        enabled: false
      enabled: false


server:
  port: 7070
  tomcat:
    uri-encoding: UTF-8

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
management:
  endpoints:
    web:
      expose: "*"

