server:
  port: 8998
  tomcat:
    uri-encoding: UTF-8
    # tomcat虚拟路径
    basedir: show/tomcat

spring:
  application:
    name: sc-service-show
  profiles:
    include: info,mysql
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  thymeleaf:
    mode: HTML5
    cache: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    # 是否将自己的IP注册到Server，不设或设为false将OS的hostname注册到Server
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    metadata-map:
      name: sc-service-show
      title: title
      description: DESC
      version: 1.0.0
      contact: CONTACT
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


# picture configure
preread:
  upload-path: E:/sc-service-show/preview/
  layer-upload-path: E:/sc-service-show/layer-preview/
  report-upload-path: E:/sc-service-show/test-report/
  final-report-upload-path: E:/sc-service-show/final-report/
