# 项目配置说明，通过http://ip:端口/actuator/info进行查询
info:
  app:
    name: @project.artifactId@
    title: 服务网关
    description: @project.description@
    version: @project.version@
    termsOfServiceUrl: http://localhost:8080/
    contact: CONTACT
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
