spring:
  application:
    name: gis-service-core
  profiles:
    include: info,gisapp
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  http:
    encoding:
      force: false
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8
  banner:
    charset: UTF-8
  servlet:
    multipart:
      # 配置文件传输
      enabled: true
      file-size-threshold: 0
      # 单个文件数据大小
      max-file-size: 100Mb
      # 单个请求的文件数据总上传大小
      max-request-size: 100Mb
      resolve-lazily: false

server:
  port: 8997
  tomcat:
    uri-encoding: UTF-8
    max-connections: 20000
    max-threads: 500
    accept-count: 500
    min-spare-threads: 20



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://eureka1:8761/eureka/,http://eureka2:8762/eureka/
  instance:
    # 是否将自己的IP注册到Server，不设或设为false将OS的hostname注册到Server
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
    metadata-map:
      name: gis-service-core
      title: 地理信息服务
      description: 地理信息服务
      version: 1.0.0
      contact: 中国电子科技集团公司第十五研究所
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 2


# 第三方服务模块上传存储路径
3rd:
  upload-path: /3rdlibs/



#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    prometheus:
#      enabled: true
#  metrics:
#    tags:
#      application: ${spring.application.name}
#    export:
#      prometheus:
#        enabled: true
#        step: 1m
#        descriptions: true
#      jmx:
#        enabled: true
#        step: 1m
#    web:
#      server:
#        auto-time-requests: false




#lease-renewal-interval-in-seconds: 1     每间隔1s向服务端发送一次心跳证明自己依然"存活"
#lease-expiration-duration-in-seconds: 2  告知服务端，若我2s之内没有给你发心跳，就代表我“死”了，将我剔除掉。

#lease-renewal-interval-in-seconds: 1     Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30
#lease-expiration-duration-in-seconds: 2  Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
#注意：lease-expiration-duration-in-seconds不要配置的比lease-renewal-interval-in-seconds小，否则会出问题，一会踢了，一会出来了
