#15所：cetc15
#超图:sm
#国遥新天地:ev
#北京星球时空科技有限公司:mc
#四维图新:nav
#庚图:gt

---

gisapp-services:
  # 网络地图服务
  wms:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.cetc15.wms.WMSHandler
      #server-handler-class: com.nci.gis.controller.ogc.ows.wms.WMSHandler
    - author: sm
      server-prefix: http://192.168.56.179:8090/iserver/
      server-handler-class: com.supermap.WMSHandler


  # 网络地图瓦片服务
  wmts:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.cetc15.wmts.WMTSHandler
      #server-handler-class: com.nci.gis.controller.ogc.ows.wmts.WMTSHandler
    - author: sm
      server-prefix: http://192.168.56.179:8090/iserver/
      server-handler-class: com.supermap.WMTSHandler


  # 地名检索服务
  gsplacename:
    - author: cetc15
      server-prefix: http://192.168.56.113:8888/mswss/
      server-handler-class: com.nci.gis.controller.data.placename.PlacenameHandler


  # 网络分析服务
  gsnetworkanalyze:
    - author: cetc15
      server-prefix: http://192.168.56.113:8888/mswss/
      server-handler-class: com.nci.gis.controller.data.networkanalyze.NetworkAnalyzeHandler


  # 几何计算服务
  gsgeometry:
    - author: cetc15
      server-prefix: http://192.168.56.113:8888/mswss/
      server-handler-class: com.nci.gis.controller.data.geometry.GeometryHandler


  # 地形分析服务
  gstopanalyze:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.nci.gis.controller.data.topoganalyze.Topanalyze3QHandler


  # 地图显示服务-Map资源
  gsmap:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.nci.gis.controller.function.map.MapHandler


  # 地图瓦片服务-MapTile资源
  gsmaptile:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.nci.gis.controller.function.maptile.MapTileHandler
    - author: mc
      server-prefix: http://192.168.56.253:15000
      server-handler-class: com.mc.MapTileHandler

  # 目录服务
  gscatalog:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.nci.gis.controller.data.catalog.Catalog3QHandler

  # 资源信息元数据服务
  gsmd:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.nci.gis.controller.data.metadata.Metadata3QHandler

  # 空间查询服务(3期)
  gsquery:
    - author: cetc15
      server-prefix: http://192.168.56.113:8999/gis3wss/
      server-handler-class: com.nci.gis.controller.data.query.QueryHandler

  # 空间查询服务(XF full-text search)
  gsqueryfts:
    - author: cetc15
      server-prefix: http://192.168.56.157:8999/mswss/
      server-handler-class: com.nci.gis.controller.data.queryfts.QueryFtsHandler


  # 通用适配服务-commonly_used_svc
  cus:
    server-handler-class: com.gis.CommonlyUsedSvcHandler

---

# 测试用
config-attributes:
  value: 345
  valueArray: 1,2,3,4,5,6,7,8,9
  valueList:
    - 13579
    - 24680
  valueMap:
    name: LuckyJiang
    age: 20
    sex: female
  valueMapList:
    - name: bob
      age: 21
    - name: caven
      age: 30

---
